version: '3'
services:
    kafka:
      image: spotify/kafka
      hostname: kafka
      container_name: kafka
      environment:
      - "ADVERTISED_HOST=kafka"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"
      command: >
          bash -c
          "(sleep 15s &&
          /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
          --create
          --zookeeper
          localhost:2181 --replication-factor 1 --partitions 1 --topic prices-topic &) && (supervisord -n)"
    producer:      
        image: producer
        build: ./producer
    consumer:      
        image: consumer
        build: ./consumer
        depends_on:
          - "producer"     
